// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pwqqebkbjmsxvpufosaw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InB3cXFlYmtiam1zeHZwdWZvc2F3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkxODU3MDcsImV4cCI6MjA2NDc2MTcwN30.OhsN_IJiO3q6jndP_meecnd4GcV09832XcYBTW4N0pc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);